swagger: "2.0"

info:
  title: "Rider stats service"
  version: "1.0"


schemes:
  - http
consumes:
  - application/json

paths:

  /store:
    post:
      operationId: app.instance.store
      parameters:
        - name: ride
          in: body
          required: true
          description: 'Ride to be stored.'
          schema:
            $ref: '#/definitions/Ride'
      produces:
        - application/json
      responses:
        '200':
          description: 'Successful ride information store.'
          schema:
            type: object
            properties:
              message:
                type: string
                description: 'Ride stored.'

  /stats:
    get:
      operationId: app.instance.get_stats
      parameters:
        - name: size
          in: query
          type: integer
          description: 'Number of rides per each rider to return. All available rides are returned if not set.'
      produces:
        - text/csv
      responses:
        '200':
          description: 'Successful ride statistics get.'
          schema:
            type: file

  /get:
    get:
      operationId: app.instance.get
      parameters:
        - name: size
          in: query
          type: integer
          description: 'Number of rides per each rider to return. All available rides are returned if not set.'
      produces:
        - application/json
      responses:
        '200':
          description: 'Successful rides information get.'
          schema:
            type: object

  /chart:
    get:
      operationId: app.instance.get_chart
      parameters:
        - name: size
          in: query
          type: integer
          required: false
          description: 'Number of rides per each rider to be plotted. All available rides are used if not set.'
      produces:
        - image/png
      responses:
        '200':
          description: 'Successfully retrieved scatter plot with rider stats.'
          schema:
            type: string
            format: binary


definitions:

  Ride:
   type: object
   required:
      - user_id
      - from_lat
      - from_lon
      - to_lat
      - to_lon
   properties:
     user_id:
       type: string
     from_lat:
       type: number
       format: float
     from_lon:
       type: number
       format: float
     to_lat:
       type: number
       format: float
     to_lon:
       type: number
       format: float

#     from:
#       $ref: '#/definitions/Coordinates'
#     to:
#       $ref: '#/definitions/Coordinates'

  Coordinates:
    type: object
    required:
      - lat
      - lon
    properties:
      lat:
        type: number
        format: float
      lon:
        type: number
        format: float

