swagger: "2.0"

info:
  title: "Rider stats service"
  version: "1.0"


schemes:
  - http
consumes:
  - application/json

paths:

  /store:
    post:
      summary: Stores ride information to the database.
      operationId: app.store
      parameters:
        - name: ride
          in: body
          required: true
          description: 'Ride to be stored.'
          schema:
            $ref: '#/definitions/Ride'
      produces:
        - application/json
      responses:
        '201':
          description: 'Successfully stored ride information.'
          schema:
            type: object
            properties:
              message:
                type: string
                description: 'Ride stored.'
        '400':
          description: Bad request. Pleae check input ride data.
        '500':
          description: Unexpected error.

  /stats:
    get:
      summary: Returns csv with information on {size} last riders' rides sorted by Euclidian distance.
      operationId: app.get_stats
      parameters:
        - name: size
          in: query
          type: integer
          description: 'Number of rides per each rider to return. All available rides are returned if not set.'
      produces:
        - text/csv
      responses:
        '200':
          description: 'Successfully returned ride statistics.'
          schema:
            type: file
        '404':
          description: No rides data found in database.
        '500':
          description: Unexpected error.

  /get:
    get:
      summary: Returns information on {size} last riders rides serialized in json.
      operationId: app.get
      parameters:
        - name: size
          in: query
          type: integer
          description: 'Number of rides per each rider to return. All available rides are returned if not set.'
      produces:
        - application/json
      responses:
        '200':
          description: 'Successfully returned rides information.'
          schema:
            type: object
        '404':
          description: No rides data found in database.

  /chart:
    get:
      summary: Returns scatter plot with X - rides count and Y - ride distance variance for each rider.
      operationId: app.get_chart
      parameters:
        - name: size
          in: query
          type: integer
          required: false
          description: 'Number of rides per each rider to be plotted. All available rides are used if not set.'
      produces:
        - image/png
      responses:
        '200':
          description: 'Successfully retrieved scatter plot with rider stats.'
          schema:
            type: string
            format: binary
        '404':
          description: No rides data found in database.
        '500':
          description: Unexpected error.


definitions:

  Ride:
   type: object
   required:
      - user_id
      - from_lat
      - from_lon
      - to_lat
      - to_lon
   properties:
     user_id:
       type: string
     from_lat:
       type: number
       format: float
     from_lon:
       type: number
       format: float
     to_lat:
       type: number
       format: float
     to_lon:
       type: number
       format: float

#     from:
#       $ref: '#/definitions/Coordinates'
#     to:
#       $ref: '#/definitions/Coordinates'

  Coordinates:
    type: object
    required:
      - lat
      - lon
    properties:
      lat:
        type: number
        format: float
      lon:
        type: number
        format: float

